<a href="https://colab.research.google.com/github/DeepanshuSharma1607/Fake_News_Generator_in_python/blob/main/ipl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1739]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [1740]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "IPL_ball_by_ball_updated.csv"

# Load the latest version
df_23= kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "dgsports/ipl-ball-by-ball-2008-to-2022",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

Using Colab cache for faster access to the 'ipl-ball-by-ball-2008-to-2022' dataset.

In [1741]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "deliveries_updated_ipl_upto_2025.csv"

# Load the latest version
df_ = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "dgsports/ipl-ball-by-ball-2008-to-2022",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

Using Colab cache for faster access to the 'ipl-ball-by-ball-2008-to-2022' dataset.

In [1742]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path1 = "ipl_2024_deliveries.csv"
file_path2 = "ipl_2025_deliveries.csv"
file_path3 = "ipl_2026_deliveries.csv"
# Load the latest version
df_24= kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "sahiltailor/ipl-2024-ball-by-ball-dataset",
  file_path1,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)
df_25= kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "sahiltailor/ipl-2024-ball-by-ball-dataset",
  file_path2,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)
df_26= kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "sahiltailor/ipl-2024-ball-by-ball-dataset",
  file_path3,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

Using Colab cache for faster access to the 'ipl-2024-ball-by-ball-dataset' dataset.
Using Colab cache for faster access to the 'ipl-2024-ball-by-ball-dataset' dataset.
Using Colab cache for faster access to the 'ipl-2024-ball-by-ball-dataset' dataset.

In [1743]:
df_['season']=pd.to_datetime(df_['date']).dt.year

In [1744]:
dv=[df_,df_23,df_24,df_25,df_26]
mapping = {
    'start_date':'date'
}
df_23.rename(columns=mapping, inplace=True)

In [1745]:
for df in dv:
  df['date']=pd.to_datetime(df['date'])

In [1746]:
team_mapping = {
    # Current name
    'Delhi Capitals': 'DC',
    # Old name → same short code
    'Delhi Daredevils': 'DC',

    'Punjab Kings': 'PBKS',
    'Kings XI Punjab': 'PBKS',

    'Royal Challengers Bangalore': 'RCB',
    'Royal Challengers Bengaluru': 'RCB',

    # Never changed
    'Kolkata Knight Riders': 'KKR',
    'Chennai Super Kings': 'CSK',
    'Rajasthan Royals': 'RR',
    'Mumbai Indians': 'MI',
    'Sunrisers Hyderabad': 'SRH',
    'Lucknow Super Giants': 'LSG',
    'Gujarat Titans': 'GT',

    # Dissolved teams
    'Deccan Chargers': 'DC_OLD',
    'Kochi Tuskers Kerala': 'KTK',
    'Pune Warriors': 'PWI',
    'Rising Pune Supergiants': 'RPS',
    'Rising Pune Supergiant': 'RPS',
    'Gujarat Lions': 'GL',
}


# Apply to both team columns
df_['batting_team'] = df_['batting_team'].replace(team_mapping)
df_['bowling_team'] = df_['bowling_team'].replace(team_mapping)

df_23['batting_team'] = df_23['batting_team'].replace(team_mapping)
df_23['bowling_team'] = df_23['bowling_team'].replace(team_mapping)

In [1747]:
venue_sources = [df_23, df_24, df_25, df_26]

venue_lookup = pd.concat([
    df[['date', 'batting_team', 'bowling_team', 'venue']]
    for df in venue_sources
]).drop_duplicates(subset=['date', 'batting_team', 'bowling_team'])

In [1748]:
if 'venue' in df_.columns:
    df_ = df_.drop(columns=['venue'])

df_ = df_.merge(
    venue_lookup,
    on=['date', 'batting_team', 'bowling_team'],
    how='left'
)

In [1749]:
df_.head(2)

,matchId,inning,over_ball,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,...,isWide,isNoBall,Byes,LegByes,Penalty,dismissal_kind,player_dismissed,date,season,venue
0,335982,1,0.1,0,1,KKR,RCB,SC Ganguly,BB McCullum,P Kumar,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2008-04-18,2008,M Chinnaswamy Stadium
1,335982,1,0.2,0,2,KKR,RCB,BB McCullum,SC Ganguly,P Kumar,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18,2008,M Chinnaswamy Stadium

In [1750]:
df_=df_.drop(columns=["over","ball"])

In [1751]:
df_=df_.drop(columns=["date","Penalty","non_striker"])

In [1752]:
df_26=df_26.drop(columns=["date",'match_no',"phase","fielder"])

In [1753]:
print(df_.shape)
print(df_26.shape)

(278205, 17)
(1382, 17)

In [1754]:
df_.columns

Index(['matchId', 'inning', 'over_ball', 'batting_team', 'bowling_team',
       'batsman', 'bowler', 'batsman_runs', 'extras', 'isWide', 'isNoBall',
       'Byes', 'LegByes', 'dismissal_kind', 'player_dismissed', 'season',
       'venue'],
      dtype='object')

In [1755]:
mapping = {
    "innings":"inning",
}
df_26.rename(columns=mapping, inplace=True)
df_26.columns

Index(['match_id', 'season', 'venue', 'batting_team', 'bowling_team', 'inning',
       'over', 'striker', 'bowler', 'runs_of_bat', 'extras', 'wide', 'legbyes',
       'byes', 'noballs', 'wicket_type', 'player_dismissed'],
      dtype='object')

In [1756]:
#Rename columns
mapping = {
    'matchId':'match_id',
    'over_ball':'over',
    'batsman':'striker',
    'isWide':'wide',
    'isNoBall':'noballs',
    "batsman_runs":"runs_of_bat",
    "dismissal_kind":"wicket_type",
    "LegByes":"legbyes",
    "Byes":"byes"

}
df_.rename(columns=mapping, inplace=True)

In [1757]:
df_['venue'] = (df_['venue']
             .str.split(',').str[0]
             .str.strip()
             .str.lower()
             .str.replace(' ', '_'))
df_26['venue'] = (df_26['venue']
             .str.split(',').str[0]
             .str.strip()
             .str.lower()
             .str.replace(' ', '_'))

In [1758]:
df = pd.concat([df_, df_26])
print(df.shape)
display(df.head())

(279587, 17)

,match_id,inning,over,batting_team,bowling_team,striker,bowler,runs_of_bat,extras,wide,noballs,byes,legbyes,wicket_type,player_dismissed,season,venue
0,335982,1,0.1,KKR,RCB,SC Ganguly,P Kumar,0,1,NaN,NaN,NaN,1.0,NaN,NaN,2008,m_chinnaswamy_stadium
1,335982,1,0.2,KKR,RCB,BB McCullum,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,2008,m_chinnaswamy_stadium
2,335982,1,0.3,KKR,RCB,BB McCullum,P Kumar,0,1,1.0,NaN,NaN,NaN,NaN,NaN,2008,m_chinnaswamy_stadium
3,335982,1,0.4,KKR,RCB,BB McCullum,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,2008,m_chinnaswamy_stadium
4,335982,1,0.5,KKR,RCB,BB McCullum,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,2008,m_chinnaswamy_stadium

In [1759]:
df.isnull().sum()

match_id                 0
inning                   0
over                     0
batting_team             0
bowling_team             0
striker                  0
bowler                   0
runs_of_bat              0
extras                   0
wide                269125
noballs             277042
byes                277504
legbyes             273990
wicket_type         265683
player_dismissed    265686
season                   0
venue                    0
dtype: int64

In [1760]:
df['bowling_team'].nunique()

15

In [1761]:
df.columns

Index(['match_id', 'inning', 'over', 'batting_team', 'bowling_team', 'striker',
       'bowler', 'runs_of_bat', 'extras', 'wide', 'noballs', 'byes', 'legbyes',
       'wicket_type', 'player_dismissed', 'season', 'venue'],
      dtype='object')

In [1762]:
print(df[['runs_of_bat', 'extras', 'wide',
       'noballs', 'byes', 'legbyes', 'wicket_type', 'player_dismissed']])

      runs_of_bat  extras  wide  noballs  byes  legbyes wicket_type  \
0               0       1   NaN      NaN   NaN      1.0         NaN
1               0       0   NaN      NaN   NaN      NaN         NaN
2               0       1   1.0      NaN   NaN      NaN         NaN
3               0       0   NaN      NaN   NaN      NaN         NaN
4               0       0   NaN      NaN   NaN      NaN         NaN
...           ...     ...   ...      ...   ...      ...         ...
1377            1       0   0.0      0.0   0.0      0.0         NaN
1378            0       0   0.0      0.0   0.0      0.0         NaN
1379            1       0   0.0      0.0   0.0      0.0         NaN
1380            0       0   0.0      0.0   0.0      0.0      caught
1381            0       0   0.0      0.0   0.0      0.0      bowled

         player_dismissed
0                     NaN
1                     NaN
2                     NaN
3                     NaN
4                     NaN
...                   ...
1377                  NaN
1378                  NaN
1379                  NaN
1380         Kartik Tyagi
1381  Varun Chakaravarthy

[279587 rows x 8 columns]

In [1763]:
cols_to_fix = ['runs_of_bat', 'extras', 'wide', 'noballs', 'byes', 'legbyes']
df[cols_to_fix] = df[cols_to_fix].fillna(0)

df['curr_ball_runs'] = df['runs_of_bat'] + df['extras']
total_score = df.groupby(['match_id', 'inning', 'batting_team'])['curr_ball_runs'].cumsum().reset_index()

In [1764]:
df['team_runs'] = df.groupby(['match_id','batting_team'])['curr_ball_runs'].cumsum()
df['team_runs'] = df.groupby(['match_id','batting_team'])['team_runs'].shift(1).fillna(0)

In [1765]:
df['first_innings_runs'] = np.where(df['inning'] == 1, df['team_runs'], 0)

df['second_innings_runs'] = np.where(df['inning'] == 2, df['team_runs'], 0)

In [1766]:
df

,match_id,inning,over,batting_team,bowling_team,striker,bowler,runs_of_bat,extras,wide,...,byes,legbyes,wicket_type,player_dismissed,season,venue,curr_ball_runs,team_runs,first_innings_runs,second_innings_runs
0,335982,1,0.1,KKR,RCB,SC Ganguly,P Kumar,0,1,0.0,...,0.0,1.0,NaN,NaN,2008,m_chinnaswamy_stadium,1,0.0,0.0,0.0
1,335982,1,0.2,KKR,RCB,BB McCullum,P Kumar,0,0,0.0,...,0.0,0.0,NaN,NaN,2008,m_chinnaswamy_stadium,0,1.0,1.0,0.0
2,335982,1,0.3,KKR,RCB,BB McCullum,P Kumar,0,1,1.0,...,0.0,0.0,NaN,NaN,2008,m_chinnaswamy_stadium,1,1.0,1.0,0.0
3,335982,1,0.4,KKR,RCB,BB McCullum,P Kumar,0,0,0.0,...,0.0,0.0,NaN,NaN,2008,m_chinnaswamy_stadium,0,2.0,2.0,0.0
4,335982,1,0.5,KKR,RCB,BB McCullum,P Kumar,0,0,0.0,...,0.0,0.0,NaN,NaN,2008,m_chinnaswamy_stadium,0,2.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1377,202606,2,15.2,KKR,SRH,Kartik Tyagi,Jaydev Unadkat,1,0,0.0,...,0.0,0.0,NaN,NaN,2026,eden_gardens,1,158.0,0.0,158.0
1378,202606,2,15.3,KKR,SRH,Vaibhav Arora,Jaydev Unadkat,0,0,0.0,...,0.0,0.0,NaN,NaN,2026,eden_gardens,0,159.0,0.0,159.0
1379,202606,2,15.4,KKR,SRH,Vaibhav Arora,Jaydev Unadkat,1,0,0.0,...,0.0,0.0,NaN,NaN,2026,eden_gardens,1,159.0,0.0,159.0
1380,202606,2,15.5,KKR,SRH,Kartik Tyagi,Jaydev Unadkat,0,0,0.0,...,0.0,0.0,caught,Kartik Tyagi,2026,eden_gardens,0,160.0,0.0,160.0
1381,202606,2,15.6,KKR,SRH,Varun Chakaravarthy,Jaydev Unadkat,0,0,0.0,...,0.0,0.0,bowled,Varun Chakaravarthy,2026,eden_gardens,0,160.0,0.0,160.0

In [1767]:
df['is_wicket']=df['player_dismissed'].notna().astype(int)

In [1768]:
df.columns

Index(['match_id', 'inning', 'over', 'batting_team', 'bowling_team', 'striker',
       'bowler', 'runs_of_bat', 'extras', 'wide', 'noballs', 'byes', 'legbyes',
       'wicket_type', 'player_dismissed', 'season', 'venue', 'curr_ball_runs',
       'team_runs', 'first_innings_runs', 'second_innings_runs', 'is_wicket'],
      dtype='object')

In [1769]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 279587 entries, 0 to 1381
Data columns (total 22 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   match_id             279587 non-null  int64
 1   inning               279587 non-null  int64
 2   over                 279587 non-null  float64
 3   batting_team         279587 non-null  object
 4   bowling_team         279587 non-null  object
 5   striker              279587 non-null  object
 6   bowler               279587 non-null  object
 7   runs_of_bat          279587 non-null  int64
 8   extras               279587 non-null  int64
 9   wide                 279587 non-null  float64
 10  noballs              279587 non-null  float64
 11  byes                 279587 non-null  float64
 12  legbyes              279587 non-null  float64
 13  wicket_type          13904 non-null   object
 14  player_dismissed     13901 non-null   object
 15  season               279587 non-null  int64
 16  venue                279587 non-null  object
 17  curr_ball_runs       279587 non-null  int64
 18  team_runs            279587 non-null  float64
 19  first_innings_runs   279587 non-null  float64
 20  second_innings_runs  279587 non-null  float64
 21  is_wicket            279587 non-null  int64
dtypes: float64(8), int64(7), object(7)
memory usage: 49.1+ MB

In [1770]:
df

,match_id,inning,over,batting_team,bowling_team,striker,bowler,runs_of_bat,extras,wide,...,legbyes,wicket_type,player_dismissed,season,venue,curr_ball_runs,team_runs,first_innings_runs,second_innings_runs,is_wicket
0,335982,1,0.1,KKR,RCB,SC Ganguly,P Kumar,0,1,0.0,...,1.0,NaN,NaN,2008,m_chinnaswamy_stadium,1,0.0,0.0,0.0,0
1,335982,1,0.2,KKR,RCB,BB McCullum,P Kumar,0,0,0.0,...,0.0,NaN,NaN,2008,m_chinnaswamy_stadium,0,1.0,1.0,0.0,0
2,335982,1,0.3,KKR,RCB,BB McCullum,P Kumar,0,1,1.0,...,0.0,NaN,NaN,2008,m_chinnaswamy_stadium,1,1.0,1.0,0.0,0
3,335982,1,0.4,KKR,RCB,BB McCullum,P Kumar,0,0,0.0,...,0.0,NaN,NaN,2008,m_chinnaswamy_stadium,0,2.0,2.0,0.0,0
4,335982,1,0.5,KKR,RCB,BB McCullum,P Kumar,0,0,0.0,...,0.0,NaN,NaN,2008,m_chinnaswamy_stadium,0,2.0,2.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1377,202606,2,15.2,KKR,SRH,Kartik Tyagi,Jaydev Unadkat,1,0,0.0,...,0.0,NaN,NaN,2026,eden_gardens,1,158.0,0.0,158.0,0
1378,202606,2,15.3,KKR,SRH,Vaibhav Arora,Jaydev Unadkat,0,0,0.0,...,0.0,NaN,NaN,2026,eden_gardens,0,159.0,0.0,159.0,0
1379,202606,2,15.4,KKR,SRH,Vaibhav Arora,Jaydev Unadkat,1,0,0.0,...,0.0,NaN,NaN,2026,eden_gardens,1,159.0,0.0,159.0,0
1380,202606,2,15.5,KKR,SRH,Kartik Tyagi,Jaydev Unadkat,0,0,0.0,...,0.0,caught,Kartik Tyagi,2026,eden_gardens,0,160.0,0.0,160.0,1
1381,202606,2,15.6,KKR,SRH,Varun Chakaravarthy,Jaydev Unadkat,0,0,0.0,...,0.0,bowled,Varun Chakaravarthy,2026,eden_gardens,0,160.0,0.0,160.0,1

In [1771]:
# final_scores = df[df['inning'] == 1].groupby('match_id')['team_runs'].max()
# df = df.merge(final_scores.rename('target'), on='match_id')
# df['target'] = np.where(df['inning'] == 2, df['target'] + 1, 0)
actual_totals = (df[df['inning'] == 1]
                 .groupby('match_id')['curr_ball_runs']
                 .sum()
                 .rename('target'))
df = df.merge(actual_totals, on='match_id')
df['target'] = np.where(df['inning'] == 2, df['target'] + 1, 0)

In [1772]:
df['over_'] = df['over'].astype(str).str.split('.').str[0].astype(int)
df['ball_in_over'] = (df['over'].astype(str)
                      .str.split('.')
                      .str[1]
                      .fillna(0)
                      .astype(int))

In [1773]:
df['ball_in_over'] = df['ball_in_over'].clip(upper=6)
df['balls_bowled'] = df['over_'] * 6 + df['ball_in_over']

In [1774]:
df['runs_to_win'] = np.where(
    df['inning'] == 2,
    df['target'] - df['team_runs'],
    0
)

In [1775]:
balls_remaining = (120 - df['balls_bowled']).clip(lower=0)

In [1776]:
df['curr_run_rate'] = np.where(
    df['balls_bowled'] == 0, 0,
    (df['team_runs'] * 6) / df['balls_bowled']
)

In [1777]:
df['req_run_rate'] = np.where(
    balls_remaining == 0,
    np.inf,
    (df['runs_to_win'] * 6) / balls_remaining
)
df['req_run_rate'] = df['req_run_rate'].clip(0, 36)

In [1778]:
df['req_run_rate'] = df['req_run_rate'].replace(np.inf, 100)

In [1779]:
df['crr_rrr_ratio'] = df['curr_run_rate'] / df['req_run_rate'].replace(0, np.inf)

df['crr_rrr_ratio'] = df['crr_rrr_ratio'].clip(0, 10)

df.loc[df['inning'] == 1,
       ['target', 'runs_to_win', 'req_run_rate', 'crr_rrr_ratio']] = 0

In [1780]:
df['balls_remaining'] = (20 * 6) - df['balls_bowled'].clip(lower=0)

In [1781]:
df['total_wickets'] = df.groupby(['match_id','inning'])['is_wicket'].cumsum()
df['total_wickets'] = df.groupby(['match_id','inning'])['total_wickets'].shift(1).fillna(0)
df['wickets_remaining'] = 10 - df['total_wickets']

In [1782]:
df = df.sort_values(['match_id', 'inning', 'balls_bowled'])
df['recent_wickets'] = (df.groupby(['match_id', 'inning'])['is_wicket']
                          .transform(lambda x: x.rolling(18, min_periods=1).sum())
                          .shift(1).fillna(0))

df['recent_runs'] = (df.groupby(['match_id', 'inning'])['curr_ball_runs']
                       .transform(lambda x: x.rolling(18, min_periods=1).sum())
                       .shift(1).fillna(0))

In [1783]:
df

,match_id,inning,over,batting_team,bowling_team,striker,bowler,runs_of_bat,extras,wide,...,balls_bowled,runs_to_win,curr_run_rate,req_run_rate,crr_rrr_ratio,balls_remaining,total_wickets,wickets_remaining,recent_wickets,recent_runs
278205,202601,1,0.1,SRH,RCB,Travis Head,Jacob Duffy,0,0,0.0,...,1,0.0,0.000000,0.0,0.000000,119,0.0,10.0,0.0,0.0
278206,202601,1,0.2,SRH,RCB,Travis Head,Jacob Duffy,1,0,0.0,...,2,0.0,0.000000,0.0,0.000000,118,0.0,10.0,0.0,0.0
278207,202601,1,0.3,SRH,RCB,Abhishek Sharma,Jacob Duffy,0,0,0.0,...,3,0.0,2.000000,0.0,0.000000,117,0.0,10.0,0.0,1.0
278208,202601,1,0.4,SRH,RCB,Abhishek Sharma,Jacob Duffy,6,0,0.0,...,4,0.0,1.500000,0.0,0.000000,116,0.0,10.0,0.0,1.0
278209,202601,1,0.5,SRH,RCB,Abhishek Sharma,Jacob Duffy,0,0,0.0,...,5,0.0,8.400000,0.0,0.000000,115,0.0,10.0,0.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276331,1485779,2,18.6,DC,PBKS,T Stubbs,Arshdeep Singh,4,0,0.0,...,114,12.0,10.263158,12.0,0.855263,6,4.0,6.0,0.0,37.0
276332,1485779,2,19.1,DC,PBKS,Sameer Rizvi,MP Stoinis,0,1,1.0,...,115,8.0,10.382609,9.6,1.081522,5,4.0,6.0,0.0,40.0
276333,1485779,2,19.2,DC,PBKS,Sameer Rizvi,MP Stoinis,1,0,0.0,...,116,7.0,10.344828,10.5,0.985222,4,4.0,6.0,0.0,39.0
276334,1485779,2,19.3,DC,PBKS,T Stubbs,MP Stoinis,1,0,0.0,...,117,6.0,10.307692,12.0,0.858974,3,4.0,6.0,0.0,39.0
276335,1485779,2,19.4,DC,PBKS,Sameer Rizvi,MP Stoinis,6,0,0.0,...,118,5.0,10.271186,15.0,0.684746,2,4.0,6.0,0.0,34.0

In [1784]:
df.columns

Index(['match_id', 'inning', 'over', 'batting_team', 'bowling_team', 'striker',
       'bowler', 'runs_of_bat', 'extras', 'wide', 'noballs', 'byes', 'legbyes',
       'wicket_type', 'player_dismissed', 'season', 'venue', 'curr_ball_runs',
       'team_runs', 'first_innings_runs', 'second_innings_runs', 'is_wicket',
       'target', 'over_', 'ball_in_over', 'balls_bowled', 'runs_to_win',
       'curr_run_rate', 'req_run_rate', 'crr_rrr_ratio', 'balls_remaining',
       'total_wickets', 'wickets_remaining', 'recent_wickets', 'recent_runs'],
      dtype='object')

In [1785]:
df['is_out'] = (df['player_dismissed'] == df['striker']).astype(int)

df['valid_ball'] = (df['wide'] == 0).astype(int)

season_bat = df.groupby(['season', 'striker']).agg(
    season_runs=('runs_of_bat', 'sum'),
    season_balls=('valid_ball', 'sum'),
    season_outs=('is_out', 'sum')
).reset_index().sort_values(['striker', 'season'])

# Cumsum then shift — so current season stats NOT included
season_bat['career_runs'] = season_bat.groupby('striker')['season_runs'].cumsum().shift(1).fillna(0)
season_bat['career_balls'] = season_bat.groupby('striker')['season_balls'].cumsum().shift(1).fillna(0)
season_bat['career_outs'] = season_bat.groupby('striker')['season_outs'].cumsum().shift(1).fillna(0)

# Smoothed stats
season_bat['batting_average'] = (season_bat['career_runs'] + 50) / (season_bat['career_outs'] + 2)
season_bat['career_strike_rate'] = ((season_bat['career_runs'] + 100) / (season_bat['career_balls'] + 80)) * 100

# Merge back
df = df.merge(
    season_bat[['season', 'striker', 'batting_average', 'career_strike_rate']],
    on=['season', 'striker'], how='left'
)

In [1786]:
# Aggregate per bowler per season
season_bowl = df.groupby(['season', 'bowler']).agg(
    season_runs_c=('runs_of_bat', 'sum'),
    season_balls_b=('valid_ball', 'sum'),
    season_wkts=('is_wicket', 'sum')
).reset_index().sort_values(['bowler', 'season'])

# Cumsum then shift — so current season NOT included
season_bowl['career_runs_c'] = season_bowl.groupby('bowler')['season_runs_c'].cumsum().shift(1).fillna(0)
season_bowl['career_balls_b'] = season_bowl.groupby('bowler')['season_balls_b'].cumsum().shift(1).fillna(0)
season_bowl['career_wkts'] = season_bowl.groupby('bowler')['season_wkts'].cumsum().shift(1).fillna(0)

# Smoothed stats
season_bowl['exp_bowler_eco'] = ((season_bowl['career_runs_c'] + 300) / (season_bowl['career_balls_b'] + 240)) * 6
season_bowl['exp_bowler_avg'] = (season_bowl['career_runs_c'] + 300) / (season_bowl['career_wkts'] + 10)

# Merge back
df = df.merge(
    season_bowl[['season', 'bowler', 'exp_bowler_eco', 'exp_bowler_avg']],
    on=['season', 'bowler'], how='left'
)

In [1787]:
df = df.sort_values(['season', 'match_id'])

In [1788]:
df.columns

Index(['match_id', 'inning', 'over', 'batting_team', 'bowling_team', 'striker',
       'bowler', 'runs_of_bat', 'extras', 'wide', 'noballs', 'byes', 'legbyes',
       'wicket_type', 'player_dismissed', 'season', 'venue', 'curr_ball_runs',
       'team_runs', 'first_innings_runs', 'second_innings_runs', 'is_wicket',
       'target', 'over_', 'ball_in_over', 'balls_bowled', 'runs_to_win',
       'curr_run_rate', 'req_run_rate', 'crr_rrr_ratio', 'balls_remaining',
       'total_wickets', 'wickets_remaining', 'recent_wickets', 'recent_runs',
       'is_out', 'valid_ball', 'batting_average', 'career_strike_rate',
       'exp_bowler_eco', 'exp_bowler_avg'],
      dtype='object')

In [1789]:
df.shape

(279587, 41)

In [1790]:
# final_scores = df.groupby(['match_id', 'inning'])['team_runs'].max().reset_index()
# final_scores = final_scores.pivot(index='match_id', columns='inning', values='team_runs').reset_index()
# final_scores['winner_innings'] = np.where(
#     final_scores[2] > final_scores[1], 2,
#     np.where(final_scores[2] < final_scores[1], 1, 0)
# )

# df = df.merge(final_scores[['match_id', 'winner_innings']], on='match_id', how='left')

# df['result'] = np.where(
#     (df['inning'] == 2) & (df['winner_innings'] == 2),
#     1,
#     np.where(
#         (df['inning'] == 2) & (df['winner_innings'] == 1),
#         0,
#         -1   # tie
#     )
# )
inning_totals = (df.groupby(['match_id','inning'])['curr_ball_runs']
                   .sum().reset_index()
                   .rename(columns={'curr_ball_runs':'inning_total'}))

scores_pivot = inning_totals.pivot(
    index='match_id', columns='inning', values='inning_total'
).reset_index()
scores_pivot.columns.name = None
scores_pivot.rename(columns={1:'inn1_total', 2:'inn2_total'}, inplace=True)

scores_pivot['winner_innings'] = np.where(
    scores_pivot['inn2_total'] > scores_pivot['inn1_total'], 2,
    np.where(scores_pivot['inn2_total'] < scores_pivot['inn1_total'], 1, 0)
)

df = df.merge(scores_pivot[['match_id','winner_innings']], on='match_id', how='left')

df['result'] = np.where(
    (df['inning']==2) & (df['winner_innings']==2), 1,
    np.where((df['inning']==2) & (df['winner_innings']==1), 0, -1)
)

# Sanity check — should be ~0.50 not 0.27
print("Chasing win rate:", df[df['inning']==2]['result'].value_counts(normalize=True))

Chasing win rate: result
 1    0.506534
 0    0.478317
-1    0.015149
Name: proportion, dtype: float64

In [1791]:
# df['bat_win'] = (df['batting_team'] == df['result']).astype(int)
# df['bowl_win'] = (df['bowling_team'] == df['result']).astype(int)
match_results = (df[df['inning']==2]
    .drop_duplicates('match_id')[['match_id','batting_team','bowling_team','result']])

match_results['bat_won']  = (match_results['result'] == 1).astype(int)
match_results['bowl_won'] = (match_results['result'] == 0).astype(int)

match_results = match_results.sort_values('match_id')

match_results['batting_team_perf'] = (
    match_results.groupby('batting_team')['bat_won']
    .expanding().mean().shift(1).reset_index(level=0, drop=True).fillna(0.5)
)
match_results['bowling_team_perf'] = (
    match_results.groupby('bowling_team')['bowl_won']
    .expanding().mean().shift(1).reset_index(level=0, drop=True).fillna(0.5)
)

df = df.merge(
    match_results[['match_id','batting_team_perf','bowling_team_perf']],
    on='match_id', how='left'
)

In [1793]:
df['batting_team_perf'] = (
    df.groupby('batting_team')['bat_won']
      .expanding()
      .mean()
      .shift(1)
      .reset_index(level=0, drop=True)
)

KeyError: 'Column not found: bat_won'

In [ ]:
df['bowling_team_perf'] = (
    df.groupby('bowling_team')['bowl_won']
      .expanding()
      .mean()
      .shift(1)
      .reset_index(level=0, drop=True)
)

In [ ]:
df['match_phase'] = pd.cut(df['over_'],
                            bins=[-1, 5, 14, 19],
                            labels=[0, 1, 2]).astype(int)

In [ ]:
df['first_innings_total'] = df['target'] - 1

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
drop_list = ['match_id',
     'runs_of_bat', 'extras', 'wide',
    'noballs', 'byes', 'legbyes',  'curr_ball_runs',
    'wicket_type', 'player_dismissed',  'is_wicket', 'is_out', 'winner_innings',
    'over', 'over_', 'ball_in_over', 'balls_bowled', 'valid_ball',
    'team_runs', 'first_innings_runs', 'second_innings_runs', 'target',
    # 'batsman_run_cum', 'balls_faced_cum',
    'total_wickets'
]
df = df.drop(columns=drop_list)

In [ ]:
df.info()

In [ ]:
df['pressure'] = df['req_run_rate'] - df['curr_run_rate']

In [ ]:
df['inning'].unique()

In [ ]:
df = df[df['inning'] <= 2]
df = df[df['result'] != -1]

In [ ]:
df.describe()

In [ ]:
df = df[df['inning'] == 2]
df = df[df['runs_to_win'] >= 0]
df = df[df['balls_remaining'] > 0]

In [ ]:
df.describe()

In [ ]:
df['batting_team_perf'] = df['batting_team_perf'].fillna(0)
df['bowling_team_perf'] = df['bowling_team_perf'].fillna(0)
df = df.sort_values(['season'])
train_df = df[df['season'] <= 2023]
test_df  = df[(df['season'] >= 2024) & (df['season'] <= 2026)]
x_train = train_df.drop(columns=['result', 'inning','season'])
y_train = train_df['result']
x_test = test_df.drop(columns=['result', 'inning','season'])
y_test = test_df['result']
print(f"Train: {len(x_train):,} rows | Test: {len(x_test):,} rows")
print(f"Train win%: {y_train.mean():.3f} | Test win%: {y_test.mean():.3f}")

In [ ]:
x_train.columns

In [ ]:
x_train=x_train.drop(columns=['striker', 'bowler'])

In [ ]:
x_test=x_test.drop(columns=['striker', 'bowler'])

In [ ]:
nominal_cols     = ['batting_team', 'bowling_team']
categorical_cols = ['venue']
numeric_cols = [
    'runs_to_win',
    'req_run_rate',
    'balls_remaining',
    'wickets_remaining',
    'match_phase',
    'first_innings_total',
    'pressure',
    'batting_team_perf',
    'bowling_team_perf',
    'batting_average',
    'career_strike_rate',
    'exp_bowler_eco',
    'exp_bowler_avg',
    'recent_runs',
    'recent_wickets',
]

print("Inf values in numeric cols:", np.isinf(df[numeric_cols]).values.sum())

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder, TargetEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, roc_curve, confusion_matrix,
    classification_report, log_loss, brier_score_loss
)
from xgboost import XGBClassifier

def build_preprocessor():
    return ColumnTransformer(transformers=[
        ('nominal',     OneHotEncoder(sparse_output=False, drop='first',
                                      handle_unknown='ignore'), nominal_cols),
        ('categorical', TargetEncoder(cv=5,smooth='auto'),categorical_cols),
        ('numeric',     StandardScaler(),numeric_cols),
    ])

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()
scale = neg / pos   # pass this to XGB

pipe = make_pipeline(
    build_preprocessor(),
    LogisticRegression(
        C=0.01,
        class_weight='balanced',   # ADD
        solver='liblinear',
        max_iter=1000
    )
)

xgb_pipe = make_pipeline(
    build_preprocessor(),
    XGBClassifier(
        n_estimators=500,
        max_depth=4,
        learning_rate=0.03,
        subsample=0.7,
        colsample_bytree=0.7,
        reg_lambda=5,
        reg_alpha=1,
        min_child_weight=15,
        gamma=1,
        scale_pos_weight=scale,
        early_stopping_rounds=30,
        eval_metric='auc',
        random_state=42
    )
)

In [ ]:
# Drop the leaky pre-computed columns before CV
train_df = train_df.drop(columns=['batting_team_perf', 'bowling_team_perf'])
test_df  = test_df.drop(columns=['batting_team_perf', 'bowling_team_perf'])

def make_team_perf(fold_df):
    mr = (fold_df[fold_df['inning'] == 2]
          .drop_duplicates('match_id')
          [['match_id', 'batting_team', 'bowling_team', 'result']]
          .sort_values('match_id').copy())
    mr['bat_won']  = (mr['result'] == 1).astype(int)
    mr['bowl_won'] = (mr['result'] == 0).astype(int)
    mr['batting_team_perf'] = (mr.groupby('batting_team')['bat_won']
        .expanding().mean().shift(1)
        .reset_index(level=0, drop=True).fillna(0.5))
    mr['bowling_team_perf'] = (mr.groupby('bowling_team')['bowl_won']
        .expanding().mean().shift(1)
        .reset_index(level=0, drop=True).fillna(0.5))
    return mr[['match_id', 'batting_team_perf', 'bowling_team_perf']]

seasons       = sorted(train_df['season'].unique())
cv_scores_lr  = []
cv_scores_xgb = []

for i in range(5, len(seasons)):
    train_seasons = seasons[:i]
    val_season    = seasons[i]

    tr_raw = train_df[train_df['season'].isin(train_seasons)].copy()
    vl_raw = train_df[train_df['season'] == val_season].copy()

    # Recompute team perf using only this fold's training data
    perf = make_team_perf(tr_raw)
    tr_raw = tr_raw.merge(perf, on='match_id', how='left')
    tr_raw[['batting_team_perf', 'bowling_team_perf']] = \
        tr_raw[['batting_team_perf', 'bowling_team_perf']].fillna(0.5)

    # For val, use the last known perf from training (most recent match)
    last_perf = perf.iloc[-1]
    vl_raw['batting_team_perf'] = last_perf['batting_team_perf']
    vl_raw['bowling_team_perf'] = last_perf['bowling_team_perf']

    X_tr  = tr_raw.drop(columns=['result', 'inning', 'season'])
    y_tr  = tr_raw['result']
    X_val = vl_raw.drop(columns=['result', 'inning', 'season'])
    y_val = vl_raw['result']

    # LR — no change needed
    pipe.fit(X_tr, y_tr)
    lr_acc = accuracy_score(y_val, pipe.predict(X_val))
    lr_auc = roc_auc_score(y_val, pipe.predict_proba(X_val)[:, 1])
    cv_scores_lr.append((lr_acc, lr_auc))

    # XGB — pass eval_set for early stopping
    xgb_pipe.fit(
        X_tr, y_tr,
        xgbclassifier__eval_set=[(X_val, y_val)],
        xgbclassifier__verbose=False
    )
    xgb_acc = accuracy_score(y_val, xgb_pipe.predict(X_val))
    xgb_auc = roc_auc_score(y_val, xgb_pipe.predict_proba(X_val)[:, 1])
    cv_scores_xgb.append((xgb_acc, xgb_auc))

    print(f"{train_seasons[-1]} → {val_season:<8} {lr_acc:>7.3f} {lr_auc:>7.3f}  {xgb_acc:>8.3f} {xgb_auc:>8.3f}")

In [ ]:
lr_cv  = np.mean(cv_scores_lr,  axis=0)
xgb_cv = np.mean(cv_scores_xgb, axis=0)
print("─" * 57)
print(f"{'CV Mean':<18} {lr_cv[0]:>7.3f} {lr_cv[1]:>7.3f}  {xgb_cv[0]:>8.3f} {xgb_cv[1]:>8.3f}")

In [ ]:
pipe.fit(x_train, y_train)
xgb_pipe.fit(
    x_train, y_train,
    xgbclassifier__eval_set=[(x_test, y_test)],
    xgbclassifier__verbose=False
)

In [ ]:
lr_train_prob  = pipe.predict_proba(x_train)[:, 1]
print(f"lr_train_prob shape: {lr_train_prob.shape}")
lr_test_prob   = pipe.predict_proba(x_test)[:, 1]
print(f"lr_test_prob shape: {lr_test_prob.shape}")
lr_train_pred  = pipe.predict(x_train)
print(f"lr_train_pred shape: {lr_train_pred.shape}")
lr_test_pred   = pipe.predict(x_test)
print(f"lr_test_pred shape: {lr_test_pred.shape}")

xgb_train_prob = xgb_pipe.predict_proba(x_train)[:, 1]
print(f"xgb_train_prob shape: {xgb_train_prob.shape}")
xgb_test_prob  = xgb_pipe.predict_proba(x_test)[:, 1]
print(f"xgb_test_prob shape: {xgb_test_prob.shape}")
xgb_train_pred = xgb_pipe.predict(x_train)
print(f"xgb_train_pred shape: {xgb_train_pred.shape}")
xgb_test_pred  = xgb_pipe.predict(x_test)
print(f"xgb_test_pred shape: {xgb_test_pred.shape}")

ens_test_prob  = 0.65 * xgb_test_prob + 0.35 * lr_test_prob
ens_test_pred  = (ens_test_prob >= 0.5).astype(int)
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

In [ ]:
def print_metrics(name, y_true, y_pred, y_prob):
    print(f"\n{'='*45}\n  {name}\n{'='*45}")
    print(f"  Accuracy  : {accuracy_score(y_true, y_pred):.4f}")
    print(f"  Precision : {precision_score(y_true, y_pred):.4f}")
    print(f"  Recall    : {recall_score(y_true, y_pred):.4f}")
    print(f"  F1        : {f1_score(y_true, y_pred):.4f}")
    print(f"  ROC-AUC   : {roc_auc_score(y_true, y_prob):.4f}")
    print(f"  Log Loss  : {log_loss(y_true, y_prob):.4f}")
    print(f"  Brier     : {brier_score_loss(y_true, y_prob):.4f}")
    print(classification_report(y_true, y_pred,
          target_names=['Bowling Wins', 'Batting Wins']))

for header, rows in [
    ("LOGISTIC REGRESSION", [
        ("LR  — Train", y_train, lr_train_pred,  lr_train_prob),
        ("LR  — Test",  y_test,  lr_test_pred,   lr_test_prob),
    ]),
    ("XGBOOST", [
        ("XGB — Train", y_train, xgb_train_pred, xgb_train_prob),
        ("XGB — Test",  y_test,  xgb_test_pred,  xgb_test_prob),
    ]),
]:
    print("\n" + "★"*45 + f"\n   {header}\n" + "★"*45)
    for row in rows:
        print_metrics(*row)

In [ ]:
print("\n" + "="*58)
print(f"{'SUMMARY':^58}")
print("="*58)
print(f"{'Model':<24} {'Split':<7} {'Acc':>6} {'F1':>6} {'AUC':>7}")
print("-"*58)

for name, yt, yp, yprob, split in [
    ('Logistic Regression',  y_train, lr_train_pred,  lr_train_prob,  'Train'),
    ('Logistic Regression',  y_test,  lr_test_pred,   lr_test_prob,   'Test'),
    ('XGBoost',              y_train, xgb_train_pred, xgb_train_prob, 'Train'),
    ('XGBoost',              y_test,  xgb_test_pred,  xgb_test_prob,  'Test'),
    ('Ensemble (0.65/0.35)', y_test,  ens_test_pred,  ens_test_prob,  'Test'),
]:
    print(f"{name:<24} {split:<7} "
          f"{accuracy_score(yt,yp):>6.4f} "
          f"{f1_score(yt,yp):>6.4f} "
          f"{roc_auc_score(yt,yprob):>7.4f}")
print("="*58)

In [ ]:
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Confusion Matrices — Test Set', fontsize=15, fontweight='bold')
for ax, preds, title in zip(axes,
                             [lr_test_pred, xgb_test_pred],
                             ['Logistic Regression', 'XGBoost']):
    sns.heatmap(confusion_matrix(y_test, preds), annot=True, fmt='d',
                cmap='Blues', ax=ax,
                xticklabels=['Bowl Wins', 'Bat Wins'],
                yticklabels=['Bowl Wins', 'Bat Wins'])
    ax.set_title(title, fontsize=13, fontweight='bold')
    ax.set_ylabel('Actual'); ax.set_xlabel('Predicted')
plt.tight_layout(); plt.show()

# — ROC Curves —
fig, ax = plt.subplots(1, figsize=(8, 6))
for probs, name, color in [
    (lr_test_prob,  'Logistic Regression', 'royalblue'),
    (xgb_test_prob, 'XGBoost',             'crimson'),
    (ens_test_prob, 'Ensemble',            'green'),
]:
    fpr, tpr, _ = roc_curve(y_test, probs)
    ax.plot(fpr, tpr, label=f'{name} (AUC={roc_auc_score(y_test, probs):.3f})',
            color=color, lw=2)
ax.plot([0,1],[0,1],'k--',lw=1,label='Random')
ax.set(xlabel='False Positive Rate', ylabel='True Positive Rate',
       title='ROC Curve — Test Set')
ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout(); plt.show()

# — Probability Distributions —
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Predicted Probability Distribution — Test Set', fontsize=14, fontweight='bold')
for ax, probs, title, color in zip(axes,
                                    [lr_test_prob, xgb_test_prob],
                                    ['Logistic Regression', 'XGBoost'],
                                    ['royalblue', 'crimson']):
    ax.hist(probs[y_test==0], bins=40, alpha=0.6, label='Bowling Wins', color='gray')
    ax.hist(probs[y_test==1], bins=40, alpha=0.6, label='Batting Wins', color=color)
    ax.axvline(0.5, color='black', linestyle='--', lw=1.5)
    ax.set(title=title, xlabel='Predicted Probability', ylabel='Count')
    ax.legend()
plt.tight_layout(); plt.show()

# — XGB Feature Importance —
feature_names = xgb_pipe.named_steps['columntransformer'].get_feature_names_out()
importance = (pd.Series(xgb_pipe.named_steps['xgbclassifier'].feature_importances_,
                        index=feature_names)
                .sort_values()
                .tail(15))
fig, ax = plt.subplots(figsize=(9, 6))
importance.plot(kind='barh', ax=ax, color='crimson', alpha=0.8)
ax.set(title='XGBoost — Top 15 Feature Importances', xlabel='Importance Score')
ax.grid(axis='x', alpha=0.3)
plt.tight_layout(); plt.show()

In [ ]:

'''
row = pd.DataFrame([{
    'batting_team': 'GT',
    'bowling_team': 'RR',
    'runs_to_win': 105,
    'curr_run_rate': round(82 / (61/6), 2),   # 8.07
    'req_run_rate': round(105 / (59/6), 2),    # 10.68
    'crr_rrr_ratio': round((82 / (61/6)) / (105 / (59/6)), 2),  # 0.76,
    'balls_remaining': 59,
    'wickets_remaining':9 , #ONLY 1 OUT
    # 'batting_average': 28,
    # 'career_strike_rate': 140,
    # 'exp_bowler_eco': 7.2,
    # 'exp_bowler_avg': 26,
    'pressure':  round((105 / (59/6)) / (82 / (61/6)), 2),
    'first_innings_total':186,
    "match_phase":1,
    "venue":"narendra_modi_stadium"
}])


[0]
[[0.6575856 0.3424144]]
RR will win the match


row = pd.DataFrame([{
    'batting_team': 'GT',
    'bowling_team': 'RR',
    'runs_to_win': 78,
    'curr_run_rate': round(100 / (79/6), 2),      # 7.59
    'req_run_rate': round(78 / (41/6), 2),         # 11.41
    'crr_rrr_ratio': round((100/(79/6)) / (78/(41/6)), 2),  # 0.67
    'balls_remaining': 41,
    'wickets_remaining': 5,
    'pressure': round((78/(41/6)) / (100/(79/6)), 2),  # 1.50
    'first_innings_total': 177,
    'match_phase': 1,   # over 13 → middle (5-14)
    "venue": "narendra_modi_stadium"
}])

pred_lr = pipe.predict(row)
pred_lr_proba=pipe.predict_proba(row)
print(pred_lr)
print(pred_lr_proba)
if pred_lr == 1:
  print(row['batting_team'].values[0], "will win the match")
else:
  print(row['bowling_team'].values[0], 'will win the match')


[0]
[[0.83415954 0.16584046]]
RR will win the match

row = pd.DataFrame([{
    'batting_team': 'GT',
    'bowling_team': 'RR',
    'runs_to_win': 34,
    'curr_run_rate': round(144 / (99/6), 2),            # 8.73
    'req_run_rate': round(34 / (21/6), 2),               # 9.71
    'crr_rrr_ratio': round((144/(99/6)) / (34/(21/6)), 2),   # 0.90
    'balls_remaining': 21,
    'wickets_remaining': 7,
    'pressure': round((34/(21/6)) / (144/(99/6)), 2),    # 1.11
    'first_innings_total': 177,
    'match_phase': 2,   # over 16 → death
    "venue": "narendra_modi_stadium"
}])

pred_lr = pipe.predict(row)
pred_lr_proba=pipe.predict_proba(row)
print(pred_lr)
print(pred_lr_proba)
if pred_lr == 1:
  print(row['batting_team'].values[0], "will win the match")
else:
  print(row['bowling_team'].values[0], 'will win the match')


[0]
[[0.58845044 0.41154956]]
RR will win the match

'''